language: rust
rust:
  - nightly

cache: cargo

before_script:
  - rustup component add rustfmt
  - rustup component add clippy || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
script:
  - cargo fmt -- --check
  - cargo clippy --all-targets -- -D warnings
  - cargo build --bin fake