os: linux
language: shell
services:
- docker
matrix:
  fast_finish: true
  include:
  - name: rustfmt/clippy-check
    language: rust
    rust:
    - nightly-2019-11-13
    cache: cargo
    before_script:
    - rustup component add rustfmt
    - rustup component add clippy
    script:
    - cargo fmt --all -- --check
    - cargo check --all --all-targets
    - cargo clippy --all --all-targets
    before_deploy:
    deploy:

before_deploy:
  - docker build -t dasinlsb/newsback:lts .
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push dasinlsb/newsback:lts
  - openssl aes-256-cbc -K $encrypted_4006a652c8d1_key -iv $encrypted_4006a652c8d1_iv -in ci/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - chmod 600 /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: ssh $SERVER_USERNAME@$SERVER_IP -o StrictHostKeyChecking=no -i /tmp/deploy_rsa 'cd /root/newsback && \
    git pull origin master && \
    docker-compose down && \
    docker-compose pull && \
    docker-compose up -d'
  on:
    branch: master

addons:
  ssh_known_hosts: $SERVER_IP