version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: newsback
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  server:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
    command: bash -c "/wait-for-it.sh db:5432 -q -- diesel setup && ./target/release/news-backend"
